plugin:
    name: TimeTracker
    description: A versatile tool for tracking work sessions across various environments
    author: Miravo
    icon: oc-icon-clock
    homepage: ''
navigation:
    timetracker:
        label: TimeTracker
        url: /
        icon: icon-clock-o
        permissions:
            - miravo.timetracker
        sideMenu:
            workers:
                label: miravo.timetracker::lang.workers
                url: miravo/timetracker/workers
                icon: icon-users
                permissions:
                    - miravo.timetracker.can_manage_workers
            worksessions:
                label: miravo.timetracker::lang.worksessions
                url: miravo/timetracker/worksessions
                icon: icon-tasks
                permissions:
                    - miravo.timetracker.can_manage_worksessions
            companies:
                label: miravo.timetracker::lang.companies
                url: miravo/timetracker/companies
                icon: icon-building
                permissions:
                    - miravo.timetracker.manage_companies
permissions:
    miravo.timetracker:
        tab: TimeTracker
        label: miravo.timetracker::lang.can_view_timetracker_menu
    miravo.timetracker.can_manage_workers:
        tab: TimeTracker
        label: miravo.timetracker::lang.can_manage_workers
    miravo.timetracker.can_manage_worksessions:
        tab: TimeTracker
        label: miravo.timetracker::lang.can_manage_worksessions
    miravo.timetracker.manage_companies:
        tab: TimeTracker
        label: miravo.timetracker::lang.can_manage_companies