list: $/miravo/timetracker/models/worksession/columns.yaml
modelClass: Miravo\Timetracker\Models\WorkSession
title: WorkSessions
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'miravo/timetracker/worksessions/update/:id'
defaultSort:
    column: created_at
    direction: desc
