list: $/miravo/timetracker/models/company/columns.yaml
modelClass: Miravo\Timetracker\Models\Company
title: Companies
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'miravo/timetracker/companies/update/:id'
