list: $/miravo/timetracker/models/worker/columns.yaml
modelClass: Miravo\Timetracker\Models\Worker
title: Workers
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'miravo/timetracker/workers/update/:id'
