workSessions:
    label: miravo.timetracker::lang.worksessions
    manage:
        form: $/miravo/timetracker/models/worksession/fields.yaml
        list: $/miravo/timetracker/models/worksession/columns.yaml
    view:
        list: $/miravo/timetracker/models/worksession/columns.yaml
        toolbarButtons: create|delete
        defaultSort:
            column: created_at
            direction: desc